version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    container_name: "rails-db"
    restart: always
    ports:
      - 15432:5432
  web:
    build:
      context: .
      dockerfile: ./server/docker/ruby/Dockerfile
      args:
        - APP_NAME=rails-docker-example
    tty: true
    container_name: "rails-web"
    volumes:
      - .:/rails-docker-example
    ports:
      - "3000:3000"
    depends_on:
      - db