version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./server/docker/ruby
      args:
        - APP_NAME=rails-docker-example
    volumes:
      - .:/rails-docker-example
    ports:
      - "3000:3000"
    depends_on:
      - db